meta_product_name: "ScandiCrush - Paris Fashion Week"
meta_title: ScandiCrush - Paris Fashion Week's Concept Showroom
meta_description: "PFW's bi-annual event presenting booming brands from the North"
meta_image: "ScandiCrush.png"                       # should exist in `app/assets/images/`

